services:
  odoo:
    environment:
      SC_LEGACY_FILE_ROOTS: /mnt/legacy-files:/mnt/legacy-online-mirror
    volumes:
      - ${SC_CUSTOMER_ADDONS_ROOT:?SC_CUSTOMER_ADDONS_ROOT is required}:/mnt/customer-addons:ro
      - ${SC_LEGACY_ATTACHMENTS_ROOT:?SC_LEGACY_ATTACHMENTS_ROOT is required}:/mnt/legacy-files:ro
      - ${SC_LEGACY_ONLINE_MIRROR_ROOT:?SC_LEGACY_ONLINE_MIRROR_ROOT is required}:/mnt/legacy-online-mirror:ro
