# -*- coding: utf-8 -*-
from . import models
from . import controllers
from . import services
from . import wizard
from .hooks import pre_init_hook, post_init_hook, ensure_core_taxes
from . import core_extension

# expose extension hooks for smart_core extension loader
from .core_extension import (  # noqa: F401
    get_intent_handler_contributions,
    get_system_init_fact_contributions,
    get_capability_contributions,
    get_capability_group_contributions,
    get_server_action_window_map_contributions,
    get_file_upload_allowed_model_contributions,
    get_file_download_allowed_model_contributions,
    get_api_data_write_allowlist_contributions,
    get_api_data_mutation_policy_contribution,
    get_intent_permission_model_acl_policy_contribution,
    get_api_data_create_execution_policy_contribution,
    get_api_data_unlink_allowed_model_contributions,
    get_model_code_mapping_contributions,
    get_create_field_fallback_contributions,
    smart_core_register,
    smart_core_extend_system_init,
    smart_core_list_capabilities_for_user,
    smart_core_capability_groups,
    smart_core_create_field_fallbacks,
    smart_core_form_business_actions,
    smart_core_identity_profile,
    smart_core_nav_scene_maps,
    smart_core_surface_aliases,
    smart_core_runtime_business_config_productization_sources,
    smart_core_resolve_record_context_config,
    smart_core_critical_scene_target_overrides,
    smart_core_critical_scene_target_route_overrides,
    smart_core_server_action_window_map,
    smart_core_file_upload_allowed_models,
    smart_core_file_download_allowed_models,
    smart_core_file_download_auth_subject,
    smart_core_legacy_visible_business_column_labels,
    smart_core_business_list_default_visibility,
    smart_core_api_data_write_allowlist,
    smart_core_api_data_mutation_policy,
    smart_core_intent_permission_model_acl_policy,
    smart_core_api_data_create_execution_policy,
    smart_core_api_data_unlink_allowed_models,
    smart_core_api_data_search_fields,
    smart_core_model_code_mapping,
    smart_core_finalize_projected_contract_data,
    smart_core_finalize_unified_page_contract_v2,
    smart_core_normalize_projected_contract_data,
    smart_core_normalize_unified_page_contract_v2,
    smart_core_scene_package_service_class,
    smart_core_scene_governance_service_class,
    smart_core_build_portal_dashboard,
    smart_core_build_capability_matrix,
    smart_core_get_project_insight,
    smart_core_build_portal_execute_button_contract,
    smart_core_build_project_execution_service,
    smart_core_build_project_dashboard_service,
    smart_core_build_project_plan_bootstrap_service,
    smart_core_build_cost_tracking_service,
    smart_core_build_payment_slice_service,
    smart_core_build_settlement_slice_service,
    smart_core_business_config_admin_group_xmlids,
    smart_core_menu_config_only_exempt_group_xmlids,
    smart_core_business_config_form_settings_refs,
    smart_core_business_config_approval_policy_refs,
    smart_core_native_config_root_menu_xmlid,
    smart_core_native_config_delivery_excluded_menu_xmlids,
    smart_core_lowcode_system_config_menu_xmlids,
    smart_core_lowcode_config_recovery_parent_menu_xmlids,
    smart_core_business_root_menu_xmlid,
    smart_core_relation_entry_policy,
    smart_core_model_specific_form_contract_policy,
    smart_core_form_field_aliases,
    smart_core_menu_delivery_token_policy,
    smart_core_business_nav_group_display_order,
    smart_core_product_policy_catalog_source,
    smart_core_product_policy_catalog_base_keys,
    smart_core_default_product_policy_specs,
    smart_core_product_policy_catalog_label,
    smart_core_platform_legacy_ownership_module,
    smart_core_resolve_release_actor_role_codes,
    smart_core_resolve_usage_actor_role_codes,
    smart_core_default_release_snapshot_role_code,
    smart_core_industry_extension_module_names,
    smart_core_app_shell_contract,
    smart_core_scene_entry_orchestrator_specs,
    smart_core_user_data_acceptance_nav_contract,
)
