{
    "name": "Smart Construction Demo Data",
    "version": "0.2.0",
    "summary": "Demo dataset for Smart Construction Core (projects, partners, light links)",
    "category": "Smart Construction",
    "depends": [
        "smart_construction_core",
        "smart_construction_bundle",
        "smart_construction_seed",
        "account",
    ],
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "data": [
        "data/base/00_dictionary.xml",
        "data/base/dictionary_demo.xml",
        "data/base/cost_demo.xml",
        "data/base/10_partners.xml",
        "data/base/15_seed_partners.xml",
        "data/base/20_projects.xml",
        "data/base/25_project_tasks.xml",
        "data/demo/sc_demo_users.xml",
        "data/demo/role_matrix_demo_users.xml",
        "data/demo/sc_demo_showcase_actions.xml",
        "data/scenario/s00_min_path/10_project_boq.xml",
        "data/scenario/s00_min_path/20_project_links.xml",
        "data/scenario/s00_min_path/30_project_revenue.xml",
        "data/scenario/s10_contract_payment/10_contracts.xml",
        "data/scenario/s10_contract_payment/20_payment_requests.xml",
        "data/scenario/s10_contract_payment/25_workbench_actions.xml",
        "data/scenario/s60_project_cockpit/10_cockpit_business_facts.xml",
        "views/ux/project_demo_banner_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
