<template>
  <div class="dashboard-page">
    <div class="page-heading"><div><h1>工作台</h1><p>欢迎回来，{{ session.displayName }}。这里汇总您当前最需要关注的项目经营信息。</p></div><el-button :loading="loading" @click="refresh"><el-icon><Refresh /></el-icon>刷新数据</el-button></div>
    <el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-16" />
    <el-row :gutter="16" class="metric-row"><el-col v-for="metric in metrics" :key="metric.label" :xs="{span:24}" :sm="{span:12}" :lg="{span:6}"><el-card shadow="never" class="metric-card"><div class="metric-top"><span>{{ metric.label }}</span><el-icon :class="metric.tone"><component :is="metric.icon" /></el-icon></div><strong>{{ metric.value }}</strong><small>{{ metric.help }}</small></el-card></el-col></el-row>
    <el-row :gutter="16"><el-col :xs="24" :lg="16"><el-card shadow="never" class="panel"><template #header><div class="panel-header"><span>项目执行概览</span><el-button link type="primary" @click="router.push('/action/project')">查看项目</el-button></div></template><el-table :data="projects" stripe empty-text="暂无项目数据"><el-table-column prop="name" label="项目名称" min-width="210" show-overflow-tooltip /><el-table-column prop="manager" label="项目经理" width="120" /><el-table-column label="执行进度" min-width="170"><template #default="{ row }"><el-progress :percentage="Number(row.progress || 0)" :stroke-width="8" /></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="statusType(row.status)" effect="light">{{ row.status || '进行中' }}</el-tag></template></el-table-column></el-table></el-card></el-col><el-col :xs="24" :lg="8"><el-card shadow="never" class="panel"><template #header><span>待处理事项</span></template><div v-if="workItems.length" class="todo-list"><div v-for="item in workItems.slice(0,5)" :key="item.id || item.key" class="todo-item"><div><strong>{{ item.title || item.label }}</strong><small>{{ item.section_label || item.section || '业务事项' }}<span v-if="item.deadline"> · {{ item.deadline }}</span></small></div><el-tag size="small" :type="priorityType(item.priority)">{{ priorityLabel(item.priority) }}</el-tag></div></div><el-empty v-else description="暂无待处理事项" :image-size="70" /><el-button v-if="workItems.length" class="full-button" text type="primary" @click="router.push('/my-work')">查看全部事项</el-button></el-card></el-col></el-row>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { Coin, DataAnalysis, List, Refresh } from '@element-plus/icons-vue'
import { fetchMyWorkSummary, listData } from '@/api/odoo'; import { useSessionStore } from '@/stores/session'; import type { Dictionary, MyWorkItem } from '@/types/contracts'
const router=useRouter(); const session=useSessionStore(); const loading=ref(false); const error=ref(''); const workItems=ref<MyWorkItem[]>([]); const projects=ref<Dictionary[]>([])
const metrics=ref([{label:'项目总数',value:'—',help:'当前账号可见项目',icon:DataAnalysis,tone:'blue'},{label:'待处理事项',value:'—',help:'需要您继续推进',icon:List,tone:'orange'},{label:'预算执行率',value:'—',help:'项目成本汇总',icon:Coin,tone:'green'},{label:'本月完成',value:'—',help:'已完成业务事项',icon:'CircleCheck',tone:'purple'}])
function priorityType(v?:string){return v==='high'||v==='urgent'?'danger':v==='medium'?'warning':'info'} function priorityLabel(v?:string){return v==='high'||v==='urgent'?'高优先级':v==='medium'?'中优先级':'普通'} function statusType(v?:string){return /完成|done|approved/i.test(v||'')?'success':/暂停|cancel/i.test(v||'')?'info':'primary'}
async function refresh(){loading.value=true;error.value='';try{const [work,projectData]=await Promise.all([fetchMyWorkSummary(),listData({model:'project.project',fields:['id','name','display_name','user_id','progress','stage_id'],limit:6,order:'write_date desc'})]);workItems.value=work.product_workspace?.sections?.flatMap((s)=>s.items||[])||work.items||work.sections?.flatMap((s)=>s.items||[])||[];projects.value=projectData.records||projectData.rows||[];metrics.value[0].value=String(projectData.total??projects.value.length);metrics.value[1].value=String(workItems.value.length)}catch(cause){error.value=cause instanceof Error?cause.message:'工作台数据加载失败';ElMessage.warning(error.value)}finally{loading.value=false}} onMounted(refresh)
</script>
<style scoped>.dashboard-page{display:grid;gap:16px}.page-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.page-heading h1{margin:0 0 8px;font-size:26px}.page-heading p{margin:0;color:#909399}.mb-16{margin-bottom:0}.metric-row{margin-bottom:0}.metric-card{border:0}.metric-top{display:flex;justify-content:space-between;align-items:center;color:#909399;font-size:13px}.metric-top .el-icon{font-size:20px}.metric-top .blue{color:#409eff}.metric-top .orange{color:#e6a23c}.metric-top .green{color:#67c23a}.metric-top .purple{color:#9b59b6}.metric-card strong{display:block;margin:14px 0 5px;font-size:28px;color:#303133}.metric-card small{color:#a8abb2}.panel{border:0}.panel-header{display:flex;justify-content:space-between;align-items:center}.todo-list{display:grid;gap:2px}.todo-item{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:14px 0;border-bottom:1px solid var(--el-border-color-lighter)}.todo-item:last-child{border-bottom:0}.todo-item strong,.todo-item small{display:block}.todo-item strong{font-size:14px;font-weight:500}.todo-item small{margin-top:6px;color:#909399}.full-button{width:100%;margin-top:8px}</style>
