<template>
  <div class="scene-page"><div class="page-heading"><div><el-breadcrumb><el-breadcrumb-item>业务场景</el-breadcrumb-item><el-breadcrumb-item>{{ sceneTitle }}</el-breadcrumb-item></el-breadcrumb><h1>{{ sceneTitle }}</h1><p>{{ payload.subtitle || payload.description || '场景内容由后端 Scene Contract 编排' }}</p></div><el-button :loading="loading" :icon="Refresh" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" /><template v-else><section v-for="zone in zones" :key="zone.key" class="scene-zone"><header v-if="zone.label"><h2>{{ zone.label }}</h2><span>{{ zone.help }}</span></header><div class="zone-grid"><scene-block-runtime v-for="block in zone.blocks" :key="block.key || block.id || block.title" :block="block" @navigate="openTarget" /></div></section><el-empty v-if="!loading&&!zones.length" description="当前场景没有可展示内容" /></template></div>
</template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import { Refresh } from '@element-plus/icons-vue';import SceneBlockRuntime from '@/components/scene/SceneBlockRuntime.vue';import { intent } from '@/api/odoo';import type { Dictionary } from '@/types/contracts'
const route=useRoute();const router=useRouter();const loading=ref(false);const error=ref('');const payload=ref<Dictionary>({});const sceneTitle=computed(()=>String(payload.value.title||payload.value.name||payload.value.page?.title||route.params.sceneKey||'业务场景'));const blockRegistry=computed(()=>{const rows=payload.value.blocks||payload.value.scene_blocks||[];return new Map((Array.isArray(rows)?rows:[]).map((block:Dictionary)=>[String(block.key||block.id),block]))});const zones=computed(()=>{const raw=payload.value.zones||payload.value.page?.zones||payload.value.zone_list||[];return(Array.isArray(raw)?raw:[]).map((zone:Dictionary,index)=>({key:String(zone.key||zone.name||index),label:String(zone.label||zone.title||zone.name||''),help:String(zone.help||zone.description||''),blocks:(Array.isArray(zone.blocks)?zone.blocks:[]).flatMap((block:any)=>typeof block==='string'?(blockRegistry.value.get(block)?[blockRegistry.value.get(block)]:[]):[block]).filter(Boolean)}))})
async function load(){loading.value=true;error.value='';try{payload.value=await intent<Dictionary>('scene.open',{scene_key:String(route.params.sceneKey),device:'web_pc'})}catch(cause){error.value=cause instanceof Error?cause.message:'场景加载失败'}finally{loading.value=false}}function openTarget(target:Dictionary){if(target.route)return void router.push(String(target.route));const model=String(target.model||target.res_model||'');const id=Number(target.record_id||target.res_id||target.id||0);if(model&&id)return void router.push({name:'Record',params:{model,id},query:{mode:'view',action_id:target.action_id||undefined,menu_id:target.menu_id||undefined}});if(model&&target.mode==='create')return void router.push({name:'Record',params:{model,id:'new'},query:{mode:'create',action_id:target.action_id||undefined,menu_id:target.menu_id||undefined}});ElMessage.info('该入口暂未声明可执行目标')}
onMounted(load)
</script>
<style scoped>.scene-page{display:grid;gap:18px}.page-heading{display:flex;justify-content:space-between;align-items:flex-end}.page-heading h1{font-size:26px;margin:12px 0 4px}.page-heading p,.scene-zone>header span{margin:0;color:var(--el-text-color-secondary)}.scene-zone{display:grid;gap:10px}.scene-zone>header{display:flex;align-items:center;gap:12px}.scene-zone h2{margin:0;font-size:17px}.zone-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:12px}.zone-grid>*{grid-column:span 6}.zone-grid>*:only-child{grid-column:1/-1}@media(max-width:900px){.zone-grid>*{grid-column:1/-1}.page-heading{align-items:flex-start;flex-direction:column}}</style>
