import type { SuggestedActionKind, SuggestedActionParsed } from './types';

const LABELS: Partial<Record<SuggestedActionKind, string>> = {
  refresh: 'Refresh now',
  retry: 'Retry now',
  go_back: 'Go back',
  open_login: 'Open login',
  relogin: 'Go to login',
  check_permission: 'View permissions',
  open_home: 'Go home',
  open_my_work_todo: 'Open todo items',
  open_my_work_done: 'Open done items',
  open_my_work_failed: 'Open failed items',
  open_my_work_section: 'Open work section',
  open_my_work: 'Open my work',
  open_usage_analytics: 'Open usage analytics',
  open_locked: 'Open locked capabilities',
  open_preview: 'Open preview capabilities',
  open_ready: 'Open ready capabilities',
  open_hidden: 'Open hidden capabilities',
  open_scene_health: 'Open scene health',
  open_scene_packages: 'Open scene packages',
  open_dashboard: 'Open dashboard',
  open_record: 'Open record',
  open_scene: 'Open scene',
  open_menu: 'Open menu',
  open_action: 'Open action',
  open_route: 'Open route',
  open_url: 'Open link',
  copy_trace: 'Copy trace',
  copy_reason: 'Copy reason',
  copy_message: 'Copy message',
  copy_error_line: 'Copy error line',
  copy_action: 'Copy action',
  copy_json_error: 'Copy error JSON',
  copy_full_error: 'Copy full error',
};

const HINTS: Partial<Record<SuggestedActionKind, string>> = {
  refresh: 'Refresh the latest data and retry.',
  retry: 'Retry this action after a short delay.',
  go_back: 'Go back to the previous page.',
  open_login: 'Open login page.',
  relogin: 'Login again and retry.',
  check_permission: 'Check role permissions, then retry.',
  open_home: 'Go back to home and continue.',
  open_my_work_todo: 'Open My Work todo section directly.',
  open_my_work_done: 'Open My Work done section directly.',
  open_my_work_failed: 'Open My Work failed section directly.',
  open_my_work_section: 'Open a specific My Work section.',
  open_my_work: 'Open My Work and continue processing pending items.',
  open_usage_analytics: 'Open usage analytics to inspect capability visibility.',
  open_locked: 'Open usage analytics filtered to locked capabilities.',
  open_preview: 'Open usage analytics filtered to preview capabilities.',
  open_ready: 'Open usage analytics filtered to ready capabilities.',
  open_hidden: 'Open usage analytics filtered to hidden capabilities.',
  open_scene_health: 'Open scene health to inspect diagnostics.',
  open_scene_packages: 'Open scene packages for governance actions.',
  open_dashboard: 'Open system dashboard.',
  open_record: 'Open the related record and resolve blockers first.',
  open_scene: 'Open the related scene and continue.',
  open_menu: 'Open the related menu and continue.',
  open_action: 'Open the related action and continue.',
  open_route: 'Open the related route and continue.',
  open_url: 'Open the provided link and continue.',
  copy_trace: 'Copy trace id for troubleshooting.',
  copy_reason: 'Copy reason code for troubleshooting.',
  copy_message: 'Copy error message for troubleshooting.',
  copy_error_line: 'Copy a compact error line for quick sharing.',
  copy_action: 'Copy raw suggested action for troubleshooting.',
  copy_json_error: 'Copy compact error JSON for troubleshooting.',
  copy_full_error: 'Copy full error bundle for troubleshooting.',
};

export function suggestedActionLabel(parsed: SuggestedActionParsed): string {
  return LABELS[parsed.kind] || '';
}

export function suggestedActionHint(parsed: SuggestedActionParsed): string {
  return HINTS[parsed.kind] || '';
}
