import type { Component } from 'vue';
import {
  TDesignAppIcon, TDesignArrowLeftIcon, TDesignArrowRightIcon, TDesignAttachIcon,
  TDesignBuildingIcon, TDesignCalendarIcon, TDesignChatIcon, TDesignCheckIcon,
  TDesignChevronDownIcon, TDesignChevronRightIcon, TDesignChevronUpIcon,
  TDesignCloseIcon, TDesignFileCsvIcon, TDesignFileExcelIcon, TDesignFileIcon,
  TDesignFileImageIcon, TDesignFilePasteIcon, TDesignFilePdfIcon,
  TDesignFilePowerpointIcon, TDesignFileWordIcon, TDesignFileZipIcon,
  TDesignFolderIcon, TDesignFolderOpenIcon, TDesignHomeIcon, TDesignLinkIcon,
  TDesignListNumberedIcon,
  TDesignLockOnIcon, TDesignMenuFoldIcon, TDesignMenuIcon, TDesignMusicIcon,
  TDesignNotificationIcon, TDesignPlusIcon, TDesignRefreshIcon, TDesignRollbackIcon,
  TDesignSearchIcon, TDesignSettingIcon, TDesignStarFilledIcon, TDesignStarIcon,
  TDesignSunnyIcon, TDesignTaskIcon, TDesignTextformatBoldIcon,
  TDesignTextformatItalicIcon, TDesignToolsIcon, TDesignUploadIcon, TDesignUserIcon,
  TDesignVideoIcon, TDesignViewColumnIcon, TDesignViewListIcon, TDesignWorkIcon,
} from '@sc/ui/icons';

export const SC_ICON_NAMES = [
  'apps', 'arrow-left', 'arrow-right', 'attach', 'bell', 'briefcase', 'building',
  'calendar', 'chat', 'check', 'chevron-down', 'chevron-right', 'chevron-up',
  'clipboard', 'close', 'columns', 'construction', 'contract', 'file-csv',
  'file-excel', 'file-image', 'file-pdf', 'file-powerpoint', 'file-text', 'file-word',
  'file-zip', 'folder', 'format-bold', 'format-italic', 'home', 'link',
  'list-numbered', 'list-unordered', 'lock', 'menu', 'music', 'panel-left',
  'plus', 'project', 'refresh', 'reply', 'search',
  'settings', 'star', 'star-outline', 'sun', 'upload', 'user', 'video',
] as const;

export type ScIconName = typeof SC_ICON_NAMES[number];

export const SC_ICON_COMPONENTS = {
  apps: TDesignAppIcon,
  'arrow-left': TDesignArrowLeftIcon,
  'arrow-right': TDesignArrowRightIcon,
  attach: TDesignAttachIcon,
  bell: TDesignNotificationIcon,
  briefcase: TDesignWorkIcon,
  building: TDesignBuildingIcon,
  calendar: TDesignCalendarIcon,
  chat: TDesignChatIcon,
  check: TDesignCheckIcon,
  'chevron-down': TDesignChevronDownIcon,
  'chevron-right': TDesignChevronRightIcon,
  'chevron-up': TDesignChevronUpIcon,
  clipboard: TDesignTaskIcon,
  close: TDesignCloseIcon,
  columns: TDesignViewColumnIcon,
  construction: TDesignToolsIcon,
  contract: TDesignFilePasteIcon,
  'file-csv': TDesignFileCsvIcon,
  'file-excel': TDesignFileExcelIcon,
  'file-image': TDesignFileImageIcon,
  'file-pdf': TDesignFilePdfIcon,
  'file-powerpoint': TDesignFilePowerpointIcon,
  'file-text': TDesignFileIcon,
  'file-word': TDesignFileWordIcon,
  'file-zip': TDesignFileZipIcon,
  folder: TDesignFolderIcon,
  'format-bold': TDesignTextformatBoldIcon,
  'format-italic': TDesignTextformatItalicIcon,
  home: TDesignHomeIcon,
  link: TDesignLinkIcon,
  'list-numbered': TDesignListNumberedIcon,
  'list-unordered': TDesignViewListIcon,
  lock: TDesignLockOnIcon,
  menu: TDesignMenuIcon,
  music: TDesignMusicIcon,
  'panel-left': TDesignMenuFoldIcon,
  plus: TDesignPlusIcon,
  project: TDesignFolderOpenIcon,
  refresh: TDesignRefreshIcon,
  reply: TDesignRollbackIcon,
  search: TDesignSearchIcon,
  settings: TDesignSettingIcon,
  star: TDesignStarFilledIcon,
  'star-outline': TDesignStarIcon,
  sun: TDesignSunnyIcon,
  upload: TDesignUploadIcon,
  user: TDesignUserIcon,
  video: TDesignVideoIcon,
} satisfies Record<ScIconName, Component>;

export function resolveScIconComponent(name: ScIconName): Component {
  return SC_ICON_COMPONENTS[name];
}
