export {
  TDesignBadge,
  TDesignButton,
  TDesignCheckbox,
  TDesignRadioGroup,
  TDesignRadio,
  TDesignDropdown,
  TDesignEmpty,
  TDesignAlert,
  TDesignDialog,
  TDesignDrawer,
  TDesignInput,
  TDesignLoading,
  TDesignTable,
  TDesignSelect,
  TDesignTabPanel,
  TDesignTabs,
  TDesignTag,
  TDesignTextarea,
  TDesignTooltip,
} from '@sc/ui/primitives';
