# -*- coding: utf-8 -*-
from . import test_action_groups_gate
from . import test_role_regression_minimal
from . import test_smoke_security
from . import test_smoke_registry
from . import test_smoke_3waymatch_flow
from . import test_smoke_validator
from . import test_budget
from . import test_contract_center
from . import test_cost_compare
from . import test_profit_compare
from . import test_stock_cost
from . import test_p0_state_closure
from . import test_install_gate
from . import test_permission_matrix
from . import test_permission_doc_sync
from . import test_high_risk_actions
from . import test_acl_matrix_gate
from . import test_record_rule_behavior_gate
from . import test_record_rule_contract_p1
from . import test_record_rule_ledger_p1
from . import test_p0_ledger_gate
from . import test_p0_finance_rr_gate
from . import test_p0_finance_ui_gate
from . import test_p0_finance_aggregate_gate
from . import test_sidebar_menu_visibility_audit
from . import test_capability_lint_gate
from . import test_capability_registry_service
from . import test_capability_contract_backend
from . import test_api_data_batch_contract_backend
from . import test_api_data_search_fields_extension
from . import test_core_extension_v2_finalize
from . import test_api_data_write_unlink_idempotency_backend
from . import test_project_context_resolver
from . import test_my_work_backend
from . import test_reason_codes_backend
from . import test_payment_request_permission
from . import test_payment_request_available_actions_backend
from . import test_payment_request_work_item_service
from . import test_payment_domain_permission_isolation
from . import test_approval_policy_toggle_backend
from . import test_scene_governance_payload_backend
from . import test_scene_package_payload_backend
from . import test_intent_surface_coverage_gate
from . import test_risk_action_execute_backend
from . import test_odoo_native_alignment_boundaries
from . import test_user_feedback_business_views
from . import test_workflow_contract_backend
from . import test_runtime_user_management
from . import test_user_module_product_closure
from . import test_role_surface_project_member
