/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ComputedRef, Ref } from 'vue';
import type { FieldDescriptor } from '@sc/schema';
import { createContractFormRecord, writeContractFormRecord } from '../../app/runtime/contractFormDataRuntime';
import { triggerOnchange } from '../../api/onchange';
import { fieldRequiresServerOnchange } from './contractActionRules';
import { fieldType, normalizeRelationIds, sanitizeUiErrorMessage } from './fieldUtils';
import { normalizeComparable, normalizeContractFieldValue } from './valueUtils';
import { buildOnchangeRequestPayload, normalizeOnchangeFieldPatch, normalizeOnchangeResponse } from './onchangeNormalization';
import { buildFormRequestContext } from './formRequestContext';
import {
  hasAmbiguousRelationMatches, relationEntry, relationInlineCreate, resolveRelationQuickFillOption,
  singleContainingRelationOption,
} from './relationDescriptor';
import { MANY2ONE_CREATE_OPTION, MANY2ONE_OPEN_RECORD_OPTION, MANY2ONE_SEARCH_MORE_OPTION, type LayoutNode, type RelationOption } from './types';

export function useRecordFormState(context: {
  formFields:ComputedRef<Record<string,FieldDescriptor>>; model:ComputedRef<string>; recordId:ComputedRef<number|null>;
  rights:ComputedRef<{write:boolean}>; formData:Record<string,unknown>; originalValues:Ref<Record<string,unknown>>;
  submissionFeedback:Ref<any>; relationKeywords:Record<string,string>; invalidatedRelationKeywords:Record<string,string>;
  clearedDynamicRelationFields:Record<string,boolean>; relationQueryTimers:Record<string,ReturnType<typeof setTimeout>>;
  relationOptions:Ref<Record<string,RelationOption[]>>; validationErrors:Ref<string[]>;
  onchangeModifiersPatch:Ref<Record<string,Record<string,unknown>>>; onchangeWarnings:Ref<any[]>; onchangeLinePatches:Ref<any[]>;
  applyingOnchangePatch:Ref<boolean>; changedFieldSet:Set<string>; dirtyFieldSet:Set<string>;
  getOnchangeTimer:()=>ReturnType<typeof setTimeout>|null; setOnchangeTimer:(timer:ReturnType<typeof setTimeout>|null)=>void;
  contractV2ActionRules:ComputedRef<any[]>; layoutNodes:ComputedRef<LayoutNode[]>; nativeStatusbar:ComputedRef<any>;
  route:any;
  isNativeFavoriteField:(name:string)=>boolean; clearDynamicRelationDependents:(name:string)=>void;
  openRelationCreateForm:(name:string,descriptor?:FieldDescriptor)=>Promise<unknown>; openRelationSearchDialog:(name:string,descriptor?:FieldDescriptor)=>Promise<unknown>;
  openRelationRecordForm:(name:string,descriptor?:FieldDescriptor)=>Promise<unknown>; relationOptionsForField:(name:string)=>RelationOption[];
  switchFormByRelationOption:(name:string,option:RelationOption)=>Promise<unknown>; queryRelationOptions:(name:string,keyword:string)=>Promise<RelationOption[]>;
  setRelationKeyword:(name:string,keyword:string)=>void; setMany2oneOption:(name:string,option:RelationOption)=>void;
  relationKeyword:(name:string)=>string; quickCreateRelation:(name:string,descriptor:FieldDescriptor|undefined,label:string)=>Promise<unknown>;
  relationUiLabel:(descriptor:FieldDescriptor|undefined,key:string,fallback?:string)=>string; relationModel:(name:string)=>string;
  relationIds:(name:string)=>number[]; upsertRelationOption:(name:string,option:RelationOption|null)=>void;
  buildOne2manyCommandValue:(name:string,mode:'write'|'onchange')=>unknown; one2manyFieldRows:(name:string)=>any[];
  initOne2manyRows:(name:string,value:unknown)=>void; applyOnchangeLinePatches:(patches:any[])=>void;
  isWritableFieldVisible:(name:string)=>boolean;
  canonicalFieldWritable?:(name:string)=>boolean|undefined;
}) {
  const inputFieldValue=(name:string)=>{const raw=context.formData[name];return raw===false||raw===null||raw===undefined?'':String(raw);};
  const comparableFieldValue=(name:string,value:unknown)=>{const type=fieldType(context.formFields.value[name]);
    if(type==='many2many')return JSON.stringify(normalizeRelationIds(value).sort((a,b)=>a-b));
    if(type==='one2many')return JSON.stringify(context.one2manyFieldRows(name).map(row=>({id:row.id||0,isNew:row.isNew,removed:row.removed,dirty:row.dirty,dirtyFields:row.dirtyFields||[],values:row.values||{}})));
    return normalizeComparable(value);};
  const isFieldWritable=(name:string)=>{const canonical=context.canonicalFieldWritable?.(name);if(typeof canonical==='boolean')return canonical;const node=context.layoutNodes.value.find(item=>item.kind==='field'&&item.name===name);if(node)return !node.readonly;return Boolean(context.nativeStatusbar.value.field===name&&!context.nativeStatusbar.value.readonly);};
  const normalizeFieldValue=(name:string,value:unknown)=>normalizeContractFieldValue({name,value,descriptor:context.formFields.value[name],originalValue:context.originalValues.value[name],buildOne2manyValue:context.buildOne2manyCommandValue});
  let onchangeTimer:ReturnType<typeof setTimeout>|null=context.getOnchangeTimer();
  const markFieldChanged=(name:string)=>{const key=String(name||'').trim();if(!key||context.applyingOnchangePatch.value)return;context.dirtyFieldSet.add(key);
    if(!fieldRequiresServerOnchange(context.contractV2ActionRules.value,key))return;context.changedFieldSet.add(key);if(onchangeTimer)clearTimeout(onchangeTimer);
    onchangeTimer=setTimeout(()=>void runOnchangeRoundtrip(),300);context.setOnchangeTimer(onchangeTimer);};
  const persistNativeFavoriteField=async(name:string,checked:boolean,previous:unknown)=>{try{await writeContractFormRecord({model:context.model.value,ids:[context.recordId.value],vals:{[name]:checked},context:{}});context.originalValues.value={...context.originalValues.value,[name]:checked};context.changedFieldSet.delete(name);context.dirtyFieldSet.delete(name);}catch{context.formData[name]=previous;context.submissionFeedback.value={kind:'error',message:'保存失败，请稍后重试。'};}};
  const setBooleanField=(name:string,checked:boolean)=>{const previous=context.formData[name];context.formData[name]=checked;if(context.isNativeFavoriteField(name)&&context.recordId.value&&context.rights.value.write){void persistNativeFavoriteField(name,checked,previous);return;}markFieldChanged(name);};
  const setMany2oneField=(name:string,descriptor:FieldDescriptor|undefined,value:string)=>{const normalized=String(value||'').trim();if(!normalized){context.formData[name]=false;context.relationKeywords[name]='';context.clearDynamicRelationDependents(name);markFieldChanged(name);return;}
    if(normalized===MANY2ONE_CREATE_OPTION){void context.openRelationCreateForm(name,descriptor);return;}if(normalized===MANY2ONE_SEARCH_MORE_OPTION){void context.openRelationSearchDialog(name,descriptor);return;}if(normalized===MANY2ONE_OPEN_RECORD_OPTION){void context.openRelationRecordForm(name,descriptor);return;}
    const id=Number(normalized);if(!Number.isFinite(id)||id<=0){context.formData[name]=false;context.relationKeywords[name]='';context.clearDynamicRelationDependents(name);markFieldChanged(name);return;}
    const normalizedId=Math.trunc(id);context.formData[name]=normalizedId;const selected=context.relationOptionsForField(name).find(option=>option.id===normalizedId);if(selected){context.relationKeywords[name]=selected.label;void context.switchFormByRelationOption(name,selected);}context.clearDynamicRelationDependents(name);markFieldChanged(name);};
  const queryMany2oneInline=(name:string,_descriptor:FieldDescriptor|undefined,value:string)=>{const keyword=String(value||'').trim();if(keyword&&context.clearedDynamicRelationFields[name]){delete context.clearedDynamicRelationFields[name];delete context.invalidatedRelationKeywords[name];}
    if(keyword&&context.invalidatedRelationKeywords[name]===keyword&&!context.formData[name]){context.relationKeywords[name]='';return;}if(keyword&&context.invalidatedRelationKeywords[name]&&context.invalidatedRelationKeywords[name]!==keyword)delete context.invalidatedRelationKeywords[name];context.relationKeywords[name]=keyword;if(!keyword){void context.queryRelationOptions(name,'');return;}context.setRelationKeyword(name,keyword);};
  const commitMany2oneInline=async(name:string,descriptor:FieldDescriptor|undefined,value:string)=>{const keyword=String(value||'').trim();if(keyword&&context.clearedDynamicRelationFields[name]&&!context.formData[name]){context.relationKeywords[name]='';return;}if(keyword&&context.invalidatedRelationKeywords[name]===keyword&&!context.formData[name]){context.relationKeywords[name]='';return;}
    if(!keyword){context.formData[name]=false;context.relationKeywords[name]='';markFieldChanged(name);return;}const currentId=Number(context.formData[name]||0);const current=context.relationOptionsForField(name).find(option=>option.id===Math.trunc(currentId));if(current&&current.label.trim().toLowerCase()===keyword.toLowerCase()){context.relationKeywords[name]=current.label;return;}
    const inline=relationInlineCreate(descriptor);const local=resolveRelationQuickFillOption(context.relationOptionsForField(name),keyword,inline.match)||singleContainingRelationOption(context.relationOptionsForField(name),keyword);if(local){context.setMany2oneOption(name,local);return;}const rows=await context.queryRelationOptions(name,keyword);const remote=resolveRelationQuickFillOption(rows,keyword,inline.match);if(remote){context.setMany2oneOption(name,remote);return;}if(rows.length===1){context.setMany2oneOption(name,rows[0]);return;}if(hasAmbiguousRelationMatches(rows,keyword,inline.match)){context.relationKeywords[name]=keyword;context.formData[name]=false;markFieldChanged(name);await context.openRelationSearchDialog(name,descriptor);return;}if(inline.enabled&&inline.createOnNoMatch){context.formData[name]=false;context.relationKeywords[name]=keyword;markFieldChanged(name);}};
  const resolvePendingInlineRelationCreates=async()=>{const issues:string[]=[];for(const node of context.layoutNodes.value){if(node.kind!=='field'||node.readonly)continue;const descriptor=context.formFields.value[node.name];const inline=relationInlineCreate(descriptor);if(fieldType(descriptor)!=='many2one'||!inline.enabled||!inline.createOnNoMatch||Number(context.formData[node.name]||0)>0)continue;const keyword=context.relationKeyword(node.name).trim();if(!keyword)continue;
      const match=resolveRelationQuickFillOption(context.relationOptionsForField(node.name),keyword,inline.match)||resolveRelationQuickFillOption(await context.queryRelationOptions(node.name,keyword),keyword,inline.match);if(match){context.setMany2oneOption(node.name,match);continue;}const rows=await context.queryRelationOptions(node.name,keyword);if(hasAmbiguousRelationMatches(rows,keyword,inline.match)){await context.openRelationSearchDialog(node.name,descriptor);issues.push(`${node.label||descriptor?.string||node.name}存在多个匹配记录，请选择具体记录`);continue;}const before=context.validationErrors.value.slice();await context.quickCreateRelation(node.name,descriptor,keyword);if(Number(context.formData[node.name]||0)<=0){issues.push(...(context.validationErrors.value.length?context.validationErrors.value:[context.relationUiLabel(descriptor,'inline_create_failed','保存时创建失败')]));context.validationErrors.value=before;}}
    return Array.from(new Set(issues)).slice(0,5);};
  const setRelationIds=(name:string,ids:number[])=>{context.formData[name]=Array.from(new Set(ids.map(Number).filter(id=>Number.isFinite(id)&&id>0).map(Math.trunc)));markFieldChanged(name);};
  const addRelationId=(name:string,option:RelationOption)=>{context.upsertRelationOption(name,option);setRelationIds(name,[...context.relationIds(name),option.id]);context.relationKeywords[name]='';};
  const quickCreateMany2manyTag=async(name:string)=>{const descriptor=context.formFields.value[name];const entry=relationEntry(descriptor);const relation=context.relationModel(name);const label=context.relationKeyword(name).trim();const inline=relationInlineCreate(descriptor);if(entry?.canCreate!==true||!relation||!label||!inline.enabled||!inline.createOnNoMatch)return;const existing=resolveRelationQuickFillOption(context.relationOptionsForField(name),label,inline.match);if(existing){addRelationId(name,existing);return;}try{const created=await createContractFormRecord({model:relation,vals:{...(entry.defaultVals||{}),[inline.nameField||'name']:label}});const id=Number(created?.id||0);if(id>0){addRelationId(name,{id:Math.trunc(id),label});await context.queryRelationOptions(name,'');}}catch(error){context.validationErrors.value=[sanitizeUiErrorMessage(error instanceof Error?error.message:error,context.relationUiLabel(descriptor,'quick_create_failed'))];}};
  const resolvePendingMany2manyTagCreates=async()=>{const issues:string[]=[];for(const [name,raw] of Object.entries(context.relationKeywords)){const keyword=String(raw||'').trim();if(!keyword||!isFieldWritable(name)||!Array.isArray(context.formData[name])||!context.relationModel(name))continue;const descriptor=context.formFields.value[name];const inline=relationInlineCreate(descriptor);if(!inline.enabled||!inline.createOnNoMatch)continue;const label=context.layoutNodes.value.find(node=>node.kind==='field'&&node.name===name)?.label||descriptor?.string||name;const match=resolveRelationQuickFillOption(context.relationOptionsForField(name),keyword,inline.match)||resolveRelationQuickFillOption(await context.queryRelationOptions(name,keyword),keyword,inline.match);if(match){addRelationId(name,match);continue;}const rows=await context.queryRelationOptions(name,keyword);if(hasAmbiguousRelationMatches(rows,keyword,inline.match)){issues.push(`${label}存在多个匹配记录，请选择具体记录`);continue;}const before=context.validationErrors.value.slice();await quickCreateMany2manyTag(name);if(context.relationKeyword(name).trim()){issues.push(...(context.validationErrors.value.length?context.validationErrors.value:[context.relationUiLabel(descriptor,'inline_create_failed','保存时创建失败')]));context.validationErrors.value=before;}}return Array.from(new Set(issues)).slice(0,5);};
  const setSelectionField=(name:string,value:string)=>{context.formData[name]=value||false;markFieldChanged(name);};
  const setRelationMultiField=(name:string,target:HTMLSelectElement)=>setRelationIds(name,Array.from(target.selectedOptions).map(item=>Number(item.value)));
  const setTextField=(name:string,value:string)=>{context.formData[name]=value;markFieldChanged(name);};
  const buildOnchangeValues=()=>buildOnchangeRequestPayload({fields:context.formFields.value,formData:context.formData,originalValues:context.originalValues.value,recordId:context.recordId.value,buildOne2manyValue:context.buildOne2manyCommandValue});
  async function runOnchangeRoundtrip(){if(!context.model.value||!context.changedFieldSet.size)return;const changed=Array.from(context.changedFieldSet);context.changedFieldSet.clear();try{const response=await triggerOnchange({model:context.model.value,res_id:context.recordId.value,values:buildOnchangeValues(),changed_fields:changed,context:buildFormRequestContext(context.route.query)});const {patch,modifiersPatch,linePatches,warnings}=normalizeOnchangeResponse(response);context.onchangeWarnings.value=warnings;context.onchangeLinePatches.value=linePatches;if(Object.keys(modifiersPatch).length)context.onchangeModifiersPatch.value={...context.onchangeModifiersPatch.value,...modifiersPatch};
      if(Object.keys(patch).length){context.applyingOnchangePatch.value=true;Object.entries(patch).forEach(([name,value])=>{if(!(name in context.formFields.value))return;const node=context.layoutNodes.value.find(item=>item.kind==='field'&&item.name===name);const normalized=normalizeOnchangeFieldPatch({descriptor:context.formFields.value[name],readonly:Boolean(node?.readonly||context.formFields.value[name]?.readonly),value});if(normalized.kind==='x2many'){context.formData[name]=normalized.value;if(normalized.fieldType==='one2many')context.initOne2manyRows(name,context.formData[name]);}else if(normalized.kind==='many2one'){context.upsertRelationOption(name,normalized.option);context.formData[name]=normalized.value;context.relationKeywords[name]=normalized.keyword||'';}else context.formData[name]=normalized.value;});context.applyingOnchangePatch.value=false;}if(linePatches.length){context.applyingOnchangePatch.value=true;context.applyOnchangeLinePatches(linePatches);context.applyingOnchangePatch.value=false;}}catch{/* Onchange preserves current values when the optional roundtrip fails. */}}
  const collectWritableValues=()=>{const values=context.layoutNodes.value.filter(node=>node.kind==='field'&&!node.readonly&&context.isWritableFieldVisible(node.name)).reduce<Record<string,unknown>>((output,node)=>{if(context.recordId.value&&!context.dirtyFieldSet.has(node.name))return output;const value=normalizeFieldValue(node.name,context.formData[node.name]);const type=fieldType(node.descriptor);if((type==='many2many'||type==='one2many')&&Array.isArray(value)&&!value.length)return output;output[node.name]=value;return output;},{});
    // Native forms legitimately use invisible companion fields (for example a
    // Binary field's `filename`) and onchange-updated technical values.  If the
    // UI explicitly changed such a field, persist it even though it has no
    // visible layout node; the native model/ACL remains the write authority.
    for(const name of context.dirtyFieldSet){if(name in values)continue;const descriptor=context.formFields.value[name];if(!descriptor||descriptor.readonly===true)continue;values[name]=normalizeFieldValue(name,context.formData[name]);}
    const status=context.nativeStatusbar.value.field;if(context.recordId.value&&status&&context.dirtyFieldSet.has(status)&&!context.nativeStatusbar.value.readonly&&status in context.formFields.value&&!(status in values))values[status]=normalizeFieldValue(status,context.formData[status]);return values;};
  return {addRelationId,collectWritableValues,commitMany2oneInline,comparableFieldValue,inputFieldValue,isFieldWritable,markFieldChanged,normalizeFieldValue,queryMany2oneInline,quickCreateMany2manyTag,resolvePendingInlineRelationCreates,resolvePendingMany2manyTagCreates,setBooleanField,setMany2oneField,setRelationIds,setRelationMultiField,setSelectionField,setTextField};
}
