# ======================================================
# ==================== Help ============================
# ======================================================
.PHONY: help
help:
	@echo "Targets:"
	@echo "  make up/down/restart/logs/ps/odoo-shell"
	@echo "  make env.matrix.check   # 校验 dev/test/prod 三环境必需变量与 DB 参数优先级"
	@echo "  make deploy.prod.sim.oneclick ENV=test ENV_FILE=.env.prod.sim"
	@echo "  make prod.sim.fresh.replay ENV=test ENV_FILE=.env.prod.sim PROD_SIM_FRESH_REPLAY=1   # prod-sim 从零重建+完整重放+验收"
	@echo "  make prod.sim.data.replay DB_NAME=<name>   # 阶段1：只重放导入数据，不做用户可用初始化"
	@echo "  make prod.sim.business.usable.init DB_NAME=<name>   # 阶段2：刷新正式投影并验收用户可直接使用"
	@echo "  make prod.sim.replay.then.usable.init DB_NAME=<name>   # 阶段1+阶段2"
	@echo "  make verify.prod.sim.isolation   # prod-sim 一键隔离验证"
	@echo "  make verify.prod.sim.isolation.quick   # prod-sim 快速隔离验证（不reset）"
	@echo "  make db.reset DB=<name> | demo.reset DB=<name> | gate.demo"
	@echo "  make verify.platform_baseline|verify.business_baseline|verify.baseline.all DB_NAME=<name>"
	@echo "  make gate.platform_baseline|gate.business_baseline|gate.baseline.all DB_NAME=<name>"
	@echo "  make verify.portal.scene_observability_preflight_smoke.container DB_NAME=<name>"
	@echo "  make verify.portal.scene_observability_preflight.refresh.container DB_NAME=<name>"
	@echo "  make verify.portal.scene_observability_preflight.latest"
	@echo "  make verify.portal.scene_observability_preflight.report"
	@echo "  make verify.portal.scene_observability.structure_guard"
	@echo "  make verify.baseline.freeze_guard"
	@echo "  make verify.scene.runtime_boundary.gate"
	@echo "  make verify.scene.delivery.readiness.role_matrix   # 角色矩阵严格验收（pm/executive/finance/ops）"
	@echo "  make verify.scene.delivery.readiness.role_company_matrix   # 角色+公司双矩阵严格验收"
	@echo "  make verify.scene.delivery.readiness"
	@echo "  make verify.scene.legacy.bundle | verify.scene.legacy.all"
	@echo "  make verify.scene.legacy.contract.guard   # alias to verify.scene.legacy_contract.guard"
	@echo "  make verify.scene.contract_path.gate"
	@echo "  make verify.boundary.guard | verify.contract.snapshot"
	@echo "  make verify.mode.filter | verify.capability.schema | verify.scene.schema"
	@echo "  make verify.seed.demo.isolation | verify.contract.ordering.smoke"
	@echo "  make verify.business.increment.preflight [BUSINESS_INCREMENT_PROFILE=base|strict]"
	@echo "  make verify.business.increment.readiness.brief [BUSINESS_INCREMENT_PROFILE=base|strict]"
	@echo "  make verify.portal.scene_observability_smoke.container DB_NAME=<name>"
	@echo "  make verify.portal.scene_observability_strict.container DB_NAME=<name>"
	@echo "  make mod.install MODULE=... [DB=...] | mod.upgrade MODULE=... [DB=...]"
	@echo "  make policy.apply.business_full DB=<name> | smoke.business_full DB=<name>"
	@echo "  make policy.apply.role_matrix DB=<name> | smoke.role_matrix DB=<name>"
	@echo "  make demo.list | demo.load SCENARIO=... [STEP=...] | demo.load.all | demo.load.full | demo.verify"
	@echo "  make test | test.safe"
	@echo "  make ci.scene.delivery.readiness | ci.gate | ci.smoke | ci.full | ci.repro"
	@echo "  make ci.clean | ci.ps | ci.logs"
	@echo "  make diag.compose | verify.ops"
	@echo "  make admin-vis-p3.registry-audit   # isolated registry export with exact cleanup"
	@echo "  make admin-vis-p3.registry-audit.validate [REGISTRY_AUDIT_RUN_ID=...]"
	@echo "  make admin-vis-p3.registry-audit.export REGISTRY_AUDIT_RUN_ID=..."
	@echo "  make admin-vis-p3.registry-audit.cleanup REGISTRY_AUDIT_RUN_ID=..."
	@echo
	@echo "Codex SOP:"
	@echo "  make codex.fast [CODEX_MODULES=...] [CODEX_NEED_UPGRADE=1]   # 快迭代：默认不升级不重建"
	@echo "  make codex.gate [CODEX_MODULES=...] [CODEX_NEED_UPGRADE=1]   # 门禁验收：reset+contract+gate"
	@echo "  vars: CODEX_MODE=$(CODEX_MODE) CODEX_NEED_UPGRADE=$(CODEX_NEED_UPGRADE) CODEX_DB=$(CODEX_DB)"
	@echo "  make verify.codex.agent_controller | agent.controller.issue.create/install/config.check/notify.test/enable/linger.enable/status/logs"
	@echo "  make agent.feishu_bridge.install/config.check/enable/disable/status/logs"
	@echo
	@echo "Common vars:"
	@echo "  MODULE=$(MODULE) DB_NAME=$(DB_NAME) DB_CI=$(DB_CI) TEST_TAGS=$(TEST_TAGS)"
	@echo "  ENV=$(ENV) ENV_FILE=$(ENV_FILE)"
	@echo "  COMPOSE_BIN='$(COMPOSE_BIN)' COMPOSE_PROJECT_NAME='$(COMPOSE_PROJECT_NAME)'"
