# -*- coding: utf-8 -*-
from __future__ import annotations

from odoo.addons.smart_construction_scene.services.workflow_rollout_handoff import (
    build_direct_runtime_handoff,
)


SCENE_SPECS = {
    "material.center": {
        "title": "物资与分包",
        "message": "围绕材料档案、采购申请、验收、出入库、租赁和专业分包组织资源履约入口。",
        "label": "进入物资与分包",
        "route": "/s/material.center",
        "semantic": "material_resource_center_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_center",
        "family": "material_resource",
        "next_scene": "material.procurement",
        "next_scene_route": "/s/material.procurement",
    },
    "material.catalog": {
        "title": "材料档案",
        "message": "维护材料目录、规格型号和价格口径，作为采购、验收、库存和结算的基础数据。",
        "label": "进入材料档案",
        "route": "/s/material.catalog",
        "semantic": "material_catalog_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_catalog",
        "action_xmlid": "smart_construction_core.action_sc_material_product_template",
        "family": "material_catalog",
        "next_scene": "material.procurement",
        "next_scene_route": "/s/material.procurement",
    },
    "material.procurement": {
        "title": "采购协同",
        "message": "从材料计划和采购申请推进询比价、采购、验收入库和材料结算。",
        "label": "进入采购申请",
        "route": "/s/material.procurement",
        "semantic": "material_procurement_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_purchase_request",
        "action_xmlid": "smart_construction_core.action_sc_material_purchase_request",
        "family": "material_procurement",
        "next_scene": "material.acceptance",
        "next_scene_route": "/s/material.acceptance",
    },
    "material.rfq": {
        "title": "询比价",
        "message": "围绕采购需求组织供应商询价、比价和定价依据。",
        "label": "进入询比价",
        "route": "/s/material.rfq",
        "semantic": "material_rfq_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_rfq",
        "action_xmlid": "smart_construction_core.action_sc_material_rfq",
        "family": "material_procurement",
        "next_scene": "material.acceptance",
        "next_scene_route": "/s/material.acceptance",
    },
    "material.acceptance": {
        "title": "材料进场验收",
        "message": "对进场材料执行验收、入库和出库跟踪，形成库存与结算依据。",
        "label": "进入材料验收",
        "route": "/s/material.acceptance",
        "semantic": "material_acceptance_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_acceptance",
        "action_xmlid": "smart_construction_core.action_sc_material_acceptance",
        "family": "material_acceptance",
        "next_scene": "material.settlement",
        "next_scene_route": "/s/material.settlement",
    },
    "material.inbound": {
        "title": "入库单",
        "message": "记录材料验收后的入库数量、批次和项目归属。",
        "label": "进入入库单",
        "route": "/s/material.inbound",
        "semantic": "material_inbound_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_inbound",
        "action_xmlid": "smart_construction_core.action_sc_material_inbound",
        "family": "material_inventory",
        "next_scene": "material.outbound",
        "next_scene_route": "/s/material.outbound",
    },
    "material.outbound": {
        "title": "出库单",
        "message": "记录项目领用、退料和出库消耗，支撑库存与成本归集。",
        "label": "进入出库单",
        "route": "/s/material.outbound",
        "semantic": "material_outbound_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_outbound",
        "action_xmlid": "smart_construction_core.action_sc_material_outbound",
        "family": "material_inventory",
        "next_scene": "material.settlement",
        "next_scene_route": "/s/material.settlement",
    },
    "material.price_library": {
        "title": "材料价格库",
        "message": "沉淀材料价格、供应来源和结算参考价。",
        "label": "进入材料价格库",
        "route": "/s/material.price_library",
        "semantic": "material_price_library_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_price_library",
        "action_xmlid": "smart_construction_core.action_sc_material_price_library",
        "family": "material_catalog",
    },
    "material.settlement": {
        "title": "材料结算",
        "message": "按采购、验收和出入库链路汇总结算材料费用。",
        "label": "进入材料结算",
        "route": "/s/material.settlement",
        "semantic": "material_settlement_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_settlement",
        "action_xmlid": "smart_construction_core.action_sc_material_settlement",
        "family": "material_settlement",
    },
    "material.rental": {
        "title": "周转材料租赁",
        "message": "处理周转材料租赁计划、租赁单和租赁结算。",
        "label": "进入租赁计划",
        "route": "/s/material.rental",
        "semantic": "material_rental_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_rental_plan",
        "action_xmlid": "smart_construction_core.action_sc_material_rental_plan",
        "family": "material_rental",
    },
    "material.rental_order": {
        "title": "租赁单",
        "message": "登记周转材料租赁执行、数量和周期。",
        "label": "进入租赁单",
        "route": "/s/material.rental_order",
        "semantic": "material_rental_order_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_rental_order",
        "action_xmlid": "smart_construction_core.action_sc_material_rental_order",
        "family": "material_rental",
        "next_scene": "material.rental_settlement",
        "next_scene_route": "/s/material.rental_settlement",
    },
    "material.rental_settlement": {
        "title": "租赁结算",
        "message": "按租赁单和使用周期形成周转材料租赁结算。",
        "label": "进入租赁结算",
        "route": "/s/material.rental_settlement",
        "semantic": "material_rental_settlement_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_material_rental_settlement",
        "action_xmlid": "smart_construction_core.action_sc_material_rental_settlement",
        "family": "material_rental",
    },
    "labor.management": {
        "title": "劳务管理",
        "message": "按劳务计划、申请、考勤和结算组织劳务资源履约。",
        "label": "进入劳务计划",
        "route": "/s/labor.management",
        "semantic": "labor_management_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_labor_plan",
        "action_xmlid": "smart_construction_core.action_sc_labor_plan",
        "family": "labor_management",
        "next_scene": "labor.request",
        "next_scene_route": "/s/labor.request",
    },
    "labor.request": {
        "title": "劳务申请",
        "message": "按项目需求提交劳务资源申请。",
        "label": "进入劳务申请",
        "route": "/s/labor.request",
        "semantic": "labor_request_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_labor_request",
        "action_xmlid": "smart_construction_core.action_sc_labor_request",
        "family": "labor_management",
        "next_scene": "labor.attendance",
        "next_scene_route": "/s/labor.attendance",
    },
    "labor.attendance": {
        "title": "考勤记录",
        "message": "登记劳务班组出勤、工时和现场工作内容。",
        "label": "进入考勤记录",
        "route": "/s/labor.attendance",
        "semantic": "labor_attendance_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_attendance_checkin",
        "action_xmlid": "smart_construction_core.action_sc_attendance_checkin",
        "family": "labor_management",
        "next_scene": "labor.settlement",
        "next_scene_route": "/s/labor.settlement",
    },
    "labor.settlement": {
        "title": "劳务结算",
        "message": "按劳务申请、考勤和用工情况形成劳务结算。",
        "label": "进入劳务结算",
        "route": "/s/labor.settlement",
        "semantic": "labor_settlement_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_labor_settlement",
        "action_xmlid": "smart_construction_core.action_sc_labor_settlement",
        "family": "labor_management",
    },
    "equipment.management": {
        "title": "机械设备",
        "message": "按设备计划、申请、使用登记和结算组织机械设备履约。",
        "label": "进入设备计划",
        "route": "/s/equipment.management",
        "semantic": "equipment_management_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_equipment_plan",
        "action_xmlid": "smart_construction_core.action_sc_equipment_plan",
        "family": "equipment_management",
        "next_scene": "equipment.request",
        "next_scene_route": "/s/equipment.request",
    },
    "equipment.request": {
        "title": "设备申请",
        "message": "按项目需求提交机械设备申请。",
        "label": "进入设备申请",
        "route": "/s/equipment.request",
        "semantic": "equipment_request_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_equipment_request",
        "action_xmlid": "smart_construction_core.action_sc_equipment_request",
        "family": "equipment_management",
        "next_scene": "equipment.usage",
        "next_scene_route": "/s/equipment.usage",
    },
    "equipment.usage": {
        "title": "设备使用登记",
        "message": "登记设备进出场、使用台班和现场使用位置。",
        "label": "进入设备使用登记",
        "route": "/s/equipment.usage",
        "semantic": "equipment_usage_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_equipment_usage",
        "action_xmlid": "smart_construction_core.action_sc_equipment_usage",
        "family": "equipment_management",
        "next_scene": "equipment.settlement",
        "next_scene_route": "/s/equipment.settlement",
    },
    "equipment.settlement": {
        "title": "设备结算",
        "message": "按设备申请和使用登记形成机械设备结算。",
        "label": "进入设备结算",
        "route": "/s/equipment.settlement",
        "semantic": "equipment_settlement_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_equipment_settlement",
        "action_xmlid": "smart_construction_core.action_sc_equipment_settlement",
        "family": "equipment_management",
    },
    "subcontract.management": {
        "title": "专业分包",
        "message": "按分包计划、申请、登记和结算组织专业分包全过程履约。",
        "label": "进入分包计划",
        "route": "/s/subcontract.management",
        "semantic": "subcontract_management_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_subcontract_plan",
        "action_xmlid": "smart_construction_core.action_sc_subcontract_plan",
        "family": "subcontract_management",
    },
    "subcontract.request": {
        "title": "分包申请",
        "message": "承接分包计划，提交分包范围、预算和建议分包单位。",
        "label": "进入分包申请",
        "route": "/s/subcontract.request",
        "semantic": "subcontract_request_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_subcontract_request",
        "action_xmlid": "smart_construction_core.action_sc_subcontract_request",
        "family": "subcontract_management",
        "next_scene": "subcontract.register",
        "next_scene_route": "/s/subcontract.register",
    },
    "subcontract.register": {
        "title": "分包登记",
        "message": "登记分包合同、分包单位和工作范围，形成履约依据。",
        "label": "进入分包登记",
        "route": "/s/subcontract.register",
        "semantic": "subcontract_register_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_subcontract_register",
        "action_xmlid": "smart_construction_core.action_sc_subcontract_register",
        "family": "subcontract_management",
        "next_scene": "subcontract.settlement",
        "next_scene_route": "/s/subcontract.settlement",
    },
    "subcontract.settlement": {
        "title": "分包结算",
        "message": "按分包登记和履约明细形成专业分包结算。",
        "label": "进入分包结算",
        "route": "/s/subcontract.settlement",
        "semantic": "subcontract_settlement_entry",
        "menu_xmlid": "smart_construction_core.menu_sc_subcontract_settlement",
        "action_xmlid": "smart_construction_core.action_sc_subcontract_settlement",
        "family": "subcontract_management",
    },
}


def build(scene_key: str = "material.center", runtime: dict | None = None, context: dict | None = None) -> dict:
    _ = context or {}
    runtime_payload = runtime or {}
    spec = dict(SCENE_SPECS.get(scene_key) or SCENE_SPECS["material.center"])
    primary_action = {
        "label": spec["label"],
        "route": spec["route"],
        "semantic": spec["semantic"],
    }
    if spec.get("menu_xmlid"):
        primary_action["menu_xmlid"] = spec["menu_xmlid"]
    if spec.get("action_xmlid"):
        primary_action["action_xmlid"] = spec["action_xmlid"]

    fallback_strategy = {
        "type": "native_menu_compat",
        "menu_xmlid": spec.get("menu_xmlid"),
        "action_xmlid": spec.get("action_xmlid"),
        "reason": "keep construction native material and subcontract actions available while scene handoff owns the industry workflow entry",
    }
    payload = {
        "scene_key": scene_key,
        "guidance": {
            "title": spec["title"],
            "message": spec["message"],
        },
        "primary_action": primary_action,
        "fallback_strategy": fallback_strategy,
        "delivery_handoff": build_direct_runtime_handoff(
            family=spec["family"],
            user_entry=f"menu:{spec.get('menu_xmlid')}",
            final_scene=scene_key,
            primary_action=primary_action,
            required_provider="construction.material_center_provider.v1",
            fallback_policy=fallback_strategy,
            rollout_wave="wave_2",
        ),
        "runtime": {
            "role_code": runtime_payload.get("role_code"),
            "company_id": runtime_payload.get("company_id"),
        },
    }
    if spec.get("next_scene"):
        payload["next_scene"] = spec["next_scene"]
        payload["next_scene_route"] = spec.get("next_scene_route")
    return payload
